### PR TITLE
new script directory added

### PR DESCRIPTION
**Pull request by manan145**
I have added a new script directory in Malaria-Detection directory which contains an ipynb file. It loads and saves the image data set of cell images

### CODE REVIEW

**Comment by HarshCasper** [comment]
@manan145 Here are some of the changes I would like to see: 

- Keep your Filename meaningful. `test`.ipynb` is incomprehensible 
- Add a Brief Documentation using Jupyter Markdown on what your Code is doing 
- Remove all Local references and path names. They are redundant 
- Compose the File as a Script and not as a Notebook

**Comment by manan145** [comment]
so do i need to copy paste the code in a regular python file?

**Comment by HarshCasper** [comment]
Yes @manan145 

Kindly do it fast, so that I can merge the Code and award the final points

**Comment by manan145** [comment]
Actually i am going through my college mid sem exam so is it fine if i do
it this sunday?

**Comment by HarshCasper** [comment]
give @manan145 75 points

**Pull request merged**
